### ISSUE TITLE
Leading and Trailing Constraint

### ISSUE THREAD

**Issue by rehannali** [freshOS/Stevia#107]
Hi, I saw your Library, and it is awe-inspiring. I tried, but I didn't find leading and trailing constraint for chainable API. Is this API support for these constraints? If yes then where to find it?

**Comment by s4cha** [comment]
Hi @rehannali indeed there is no leading/trailing in the chain able api. (yet!)

You can use it in the "equation" style though `viewA.Leading == viewB.Trailing`
and retrieve the constraint later like so `viewA.leadingConstraint` if needed.

I think this is something we can reasonably support in a next version for sure :)

**Comment by s4cha** [comment]
This snippet would add such an api.

Let me know how this works and we can plan to integrate it in the next release :)

```swift
public extension UIView {
    
    // Leading
    
    @discardableResult
    public func leading(_ points: CGFloat) -> UIView {
        return position(.leading, points: points)
    }
    
    @discardableResult
    public func leading(_ fm: SteviaFlexibleMargin) -> UIView {
        return position(.leading, relatedBy: fm.relation, points: fm.points)
    }
    
    @discardableResult
    public func leading(_ p: SteviaPercentage) -> UIView {
        if let spv = superview {
            Leading == p.value % spv.Trailing
        }
        return self
    }
    
    // Trailing
    
    @discardableResult
    public func trailing(_ points: CGFloat) -> UIView {
        return position(.trailing, points: points)
    }
    
    @discardableResult
    public func trailing(_ fm: SteviaFlexibleMargin) -> UIView {
        return position(.trailing, relatedBy: fm.relation, points: fm.points)
    }
    
    @discardableResult
    public func trailing(_ p: SteviaPercentage) -> UIView {
        if let spv = superview {
            Trailing == p.value % spv.Leading
        }
        return self
    }
    
    func position(_ position: NSLayoutConstraint.Attribute,
                              relatedBy: NSLayoutConstraint.Relation = .equal,
                              points: CGFloat) -> UIView {
        if let spv = superview {
            let c = constraint(item: self, attribute: position,
                               relatedBy: relatedBy,
                               toItem: spv,
                               constant: points)
            spv.addConstraint(c)
        }
        return self
    }
}
```

**Comment by s4cha** [comment]
@rehannali Have you had time to try it?

**Comment by zakhej** [comment]
@s4cha thanks for hint! I've added and it works. Here is my addition:

```
// MARK: Stevia support Leading/Trailing
public extension UIView {
    @discardableResult
    func leading(_ points: CGFloat) -> UIView {
        return position(.leading, points: points)
    }
    
    @discardableResult
    func trailing(_ points: CGFloat) -> UIView {
        return position(.trailing, points: points)
    }
    
    func position(_ position: NSLayoutConstraint.Attribute,
                  relatedBy: NSLayoutConstraint.Relation = .equal,
                  points: CGFloat) -> UIView {
        if let spv = superview {
            let c = constraint(item: self, attribute: position,
                               relatedBy: relatedBy,
                               toItem: spv,
                               constant: points)
            spv.addConstraint(c)
        }
        return self
    }
    
    @discardableResult
    func fillHorizontallyLT(m: CGFloat = 0) -> UIView {
        let a: NSLayoutConstraint.Attribute = .leading
        let b: NSLayoutConstraint.Attribute = .trailing
        if let spv = superview {
            let c1 = constraint(item: self, attribute: a, toItem: spv, constant: m)
            let c2 = constraint(item: self, attribute: b, toItem: spv, constant: -m)
            spv.addConstraints([c1, c2])
        }
        return self
    }
    
    @discardableResult
    func fillContainerLT() -> UIView {
        fillHorizontallyLT(m: 0)
        fillVertically(m: 0)
        return self
    }
}
```
Unfortunately, because the extension methods contain default parameters it broke InjectionIII plugin work, so I'm awaiting when this support will be added to repo so it would be part of library instead of being an extension.

**Comment by rehannali** [comment]
@s4cha Sorry for the late reply, I've been busy in other projects. This works fine.

**Comment by mhijack** [comment]
Hi all, is there any plan of adding this in the next release? And when would that be? Thanks for all the hard work here. Loving Stevia.

**Comment by mineschan** [comment]
Hi there! I've been using Stevia for years and now our team planned to migrate the whole project to Stevia!

But as soon as we started it, we also started adding support to RTL (right to left) languages, which Stevia is still lack of support. 

Adding lead trailing as above extension works fine but I still need support of `layout()`, do your team has any plan on full RTL support?

Thanks again for great work!

**Comment by s4cha** [comment]
@rehannali @mhijack I'm looking at this at the moment.
I'm curious as to why we would need `fillHorizontallyLT()`, how is is different from `fillHorizontally()` ?

@mineschan Very happy that you chose Stevia for your project 👍 RTL is definitely the priority for the next version :)
Not sure I understand the "Apple's visual format" support for RTL though, could you elaborate on what that would look like ?

PS: Please excuse the late reply, iOS13 got us all busy 🙏

**Comment by artem-shmatkov** [comment]
> I'm curious as to why we would need `fillHorizontallyLT()`, how is is different from `fillHorizontally()` ?

`fillHorizontallyLT()` will attach view to `leading` and `trailing` constraints, and `fillHorizontally()` works with `left` and `right`. Use of `leading` and `trailing` is needed when we want to support RTL.

I do not remember why I've named it `fillHorizontallyLT`. Looks like it's better to change method name to `fillHorizontallyRTL`

**Comment by s4cha** [comment]
@artem-shmatkov Thanks a ton for the precisions. I understand that the anchors used under the hood will be different but how would this be visually different ?

**Comment by s4cha** [comment]
A first version of the PR is here: https://github.com/freshOS/Stevia/pull/127
The code is slightly different form the original extension above.

**Comment by mineschan** [comment]
> @rehannali @mhijack I'm looking at this at the moment.
> I'm curious as to why we would need `fillHorizontallyLT()`, how is is different from `fillHorizontally()` ?
> 
> @mineschan Very happy that you chose Stevia for your project 👍 RTL is definitely the priority for the next version :)
> Not sure I understand the "Apple's visual format" support for RTL though, could you elaborate on what that would look like ?
> 
> PS: Please excuse the late reply, iOS13 got us all busy 🙏

I meant the Stevia Horizontal Operators
|-view-view2-|

**Comment by mineschan** [comment]
@s4cha adding support for chainnable API is rather easy, but horizonal operators under the hood adds .left and .right

By default AutoLayout and some popular frameworks support RTL automatically, but as Stevia is using left right so people had already using it, so instead of require developers to refactor tge exisitng code, 
i have a thought to add some configures to let developers adopts RTL easily like this

`Stevia.configure().overrideLeftRightWithLeadTrailing = true`

to determine whether .left or .leading to use when adding horizontal constraints

**Comment by artem-shmatkov** [comment]
@s4cha 

> @artem-shmatkov Thanks a ton for the precisions. I understand that the anchors used under the hood will be different but how would this be visually different ?

Heh, looks like I misunderstood the concept of RTL support and somehow I thought that text in a label will be aligned LTR even in RTL environment if you attach label to `left` and `right`. Just checked it and realized that I was wrong :)
You're right, now I understand that `fillHorizontallyLT()` is useless.

**Comment by mineschan** [comment]
> @s4cha
> 
> > @artem-shmatkov Thanks a ton for the precisions. I understand that the anchors used under the hood will be different but how would this be visually different ?
> 
> Heh, looks like I misunderstood the concept of RTL support and somehow I thought that text in a label will be aligned LTR even in RTL environment if you attach label to `left` and `right`. Just checked it and realized that I was wrong :)
> You're right, now I understand that `fillHorizontallyLT()` is useless.

Talking about RTL support, not just label and text will be flipped, the whole layout should be, so in fact no .left .right should be used, even fillHorizontally, they should all goes with lead and trailing

**Comment by s4cha** [comment]
Well I guess we could replace all the right/left references in the Visual format code by their leading/trailing counterparts then, like so 👍 
```swift
postfix operator |
@discardableResult
public postfix func | (p: UIView) -> UIView {
    // return p.right(0)
    return p.trailing(0)
}
```
We have to make sure this doesn't break anything and issue a warning with the release as it's quite a big change. And can try it out starting next week and will report how this goes :)

**Comment by mineschan** [comment]
yes its very easy to replace them and also yes taking care of  exisitng users is important too.

good! please keep up the cool works!👍🏻

**Comment by s4cha** [comment]
@mineschan @artem-shmatkov @rehannali @mhijack The pre-realse

https://github.com/freshOS/Stevia/releases/tag/4.7.0
Enjoy :)

**Comment by mineschan** [comment]
#128

**Comment by s4cha** [comment]
Thanks @mineschan I'm gonna check the percent api to see If can pinpoint the issue.

**Comment by s4cha** [comment]
@rehannali This is now live in 4.7.1 :)
