### ISSUE TITLE
Stevia Problem with Swift 5

### ISSUE THREAD

**Issue by shopno111** [freshOS/Stevia#114]
Stevia Problem with Swift 5
Problem in fillContainer()

**Comment by s4cha** [comment]
@shopno111 are you still experiencing the issue with the latest version supporting Swift 5 (version 4.5.0)?

**Comment by shopno111** [comment]
Yes, still I am getting this problem

**Comment by s4cha** [comment]
Could you elaborate on what is happening? Warning, crash, unwanted behaviour ? I'd need to be able to reproduce the issue in order to debug it :)

**Comment by shopno111** [comment]
Hi,
Thanks for your response, I can't figure out specific problem. I am using https://github.com/Yummypets/YPImagePicker . On this library used your library, it's message  me "Thread 1: signal SIGABRT". and when I disable all fillContainer() where it's used, then it's work perfectly.
You can check with this project https://github.com/Yummypets/YPImagePicker. I hope from here you can figure out it quickly.

Thanks

**Comment by shopno111** [comment]
Any update on it ?

**Comment by shopno111** [comment]
I solved it by updating with your Stevia.framework file

**Comment by s4cha** [comment]
@shopno111 Thanks a ton for the context, indeed YpImagePicker needs to be updated to swift 5 asap, I will l let you know when it’s done :)

**Comment by wisnugautama** [comment]
can you tell me how exactly you do this? thanks, im a real newbie in this sort of stuff

**Comment by s4cha** [comment]
@shopno111 YPImagePicker has been updated in the meantime, fixing your issue :)
@wisnugautama  are you experiencing the same issue? Updating YPImagePicker by running
**Carthage**: `carthage update YPImagePicker`
**Cocoapods**: `pod update YPImagePicker`
will update the library.
Let me know :)

**Comment by shopno111** [comment]
> @shopno111 Thanks a ton for the context, indeed YpImagePicker needs to be updated to swift 5 asap, I will l let you know when it’s done :)

No I was update it, now it's ok

**Comment by s4cha** [comment]
Closing this as it seems resolved, the issue occurs when two different versions of the Stevia framework are used in the same project.
  
@wisnugautama don't hesitate to reach out if you have any issue :)
