### ISSUE TITLE
Binary operator '%' cannot be applied to operands of type 'Int' and 'SteviaAttribute'

### ISSUE THREAD

**Issue by fallenhaivision** [freshOS/Stevia#122]
Why do I get this error for things like
v.Width == 47 % view.Height
or 
v.Width == (view.Height * 9) / 16

Thanks

**Comment by masd-duc** [comment]
did you try to use CGFloat?

**Comment by s4cha** [comment]
@fallenhaivision This is weird, `v.Width == 47 % view.Height` work fine on my end, the complier is smart enough to assume this is a CGFloat. As @masd-duc suggested you can always
explicitly cast your value if it was previously declared as an int. Are you still experiencing the issue? If so could you provide more information about your environement?

**Comment by fallenhaivision** [comment]
CGFloat solved the issue, thank you.
