### ISSUE TITLE
 xcode  Latest Version

### ISSUE THREAD

**Issue by miaoyuxuan** [freshOS/Stevia#130]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.2

**Comment by s4cha** [comment]
Hi @miaoyuxuan Indeed a new version of Xcode is out so we have to reissue the `.framework` files (this is very annoying by the way). 
In the meantime, if you are using Carthage, you can do `carthage update Stevia --no-use-binaires`
which will compile the framework locally with your latest version of Xcode. 

Let me know if that works,
