### ISSUE TITLE
swift version

### ISSUE THREAD

**Issue by GongWeiCheng** [freshOS/Stevia#133]
Module compiled with Swift 5.1 cannot be imported by the Swift 5.1.3

**Comment by s4cha** [comment]
Hi @GongWeiCheng, Are you using Carthage, Cocoapods or Swift package manager ?

PS: Please excuse the delay I jus came back from holiday.

**Comment by GongWeiCheng** [comment]
Swift 5.1.2  can be used in latest xcode    thanks

**Comment by GongWeiCheng** [comment]
Module compiled with Swift 5.1.2 cannot be imported by the Swift 5.2    its  annoying

**Comment by s4cha** [comment]
Hi @GongWeiCheng Are you using Carthage, Cocoapods or Swift package manager ?

**Comment by GongWeiCheng** [comment]
Swift package manager
