### ISSUE TITLE
All links to http://freshos.org/ broken

### ISSUE THREAD

**Issue by max-ott** [freshOS/Stevia#134]
Just curious if this project is still worked on? All links to http://freshos.org/ seem to be broken and there is no way to access the full documentation.

**Comment by s4cha** [comment]
@max-ott Yes it is still alive and well,  the main domain expired and got squatted :/. the docs are still available here : https://freshos.github.io/SteviaDocs/
:)

**Comment by s4cha** [comment]
@max-ott the links are now updated on the readme :),  thanks for letting us know 👍
