### ISSUE TITLE
Dependency "Stevia" has no shared framework schemes

### ISSUE THREAD

**Issue by ian-schu** [freshOS/Stevia#135]
I've been using `Stevia` with CocoaPods without issue for a couple months. Nice work, btw! 👍  But now I'm switching to Carthage and having some issues.

Granted, I'm new to Carthage so it's plausible I'm doing something wrong here, _but_ ...

Cartfile:
```
github "freshOS/Stevia"
... other frameworks here ...
```

When running `carthage update` all my other dependencies seem to build just fine. However:

![image](https://user-images.githubusercontent.com/34523645/74167227-8b9ee480-4bed-11ea-8f35-a7bb03483c55.png)

Any ideas? Many thanks 🙏

**Comment by s4cha** [comment]
Hi @ian-schu sure you need to specify  the 4.7.3 version. Starting 4.8.0 (the latest version), only swift package manager will be supported.
```swift
github "freshOS/Stevia" "4.7.3"
```
By the way have you tried starting to use Swift package manager for Stevia and your other libs?
Hope this helps :)

**Comment by ian-schu** [comment]
Thanks a bunch, I'm sure this will take care of me.

I haven't tried SwiftPM yet! Still new to the iOS ecosystem so I'm doing the typical rounds through different dependency mgrs 😏

**Comment by ian-schu** [comment]
I haven't circled back to Carthage yet, but I'll go ahead and close this out since I have little doubt your fix will work. Sounds like a common problem 👍
