### ISSUE TITLE
No installation instructions to SPM

### ISSUE THREAD

**Issue by guseulalio** [freshOS/Stevia#139]
On the ReadMe file, the link points to freshos.org.
But even if I replace the .org with .github.io, it still only shows instructions for Cocoa Pods and Catharge, which, if I understood it correctly, are not to be used anymore. But nothing on Swift Package Manager.

**Comment by s4cha** [comment]
Hi at @guseulalio thanks for taking the time to post an issue. Indeed we had an issue with our previous website. I just updated the readme with the correct link at the moment.
You are correct about Carthage and Cocoapods, they are still available for legacy version for backwards compatibility's sake but the way forward is with Swift package manager.
For that you just need the url:

Select `Xcode`>`File`> `Swift Packages`>`File`>`Add Package Dependency...`  
and add `https://github.com/freshOS/Stevia`.

Let me know if that works on your side :)

**Comment by guseulalio** [comment]
I think there's an extra `File >` after `Swift Packages`.
Other than that, works great.
Thank you.

**Comment by s4cha** [comment]
Oops, will update Thanks! closing this for now.
Don't hesitate to reach out if needed :)
