### ISSUE TITLE
Request: Reduce repo size, fetching with SPM, Git takes long time

### ISSUE THREAD

**Issue by sdyalor** [freshOS/Stevia#144]
Please optimize the repo clone size
![Screen Shot 2020-06-28 at 10 54 08 PM](https://user-images.githubusercontent.com/50224521/85971257-4dcf0c80-b992-11ea-9217-e3135a4c8e86.png)
![Screen Shot 2020-06-28 at 10 53 51 PM](https://user-images.githubusercontent.com/50224521/85971261-4f98d000-b992-11ea-8098-497d22a66290.png)

**Comment by s4cha** [comment]
@sdyalor This is a very good remark! I actually never realised how big the repo was. I am going to try and prune what I can and I'll report back :)

**Comment by s4cha** [comment]
@sdyalor Ineed all the `Stevia.framework` that were generated (for Carthage) along all the releases have been accumulating. They should have never been committed anyway. By only removing them we go from 143Mb to 35MB 🎉

**Comment by s4cha** [comment]
By removing dangling Dsyms we reach 21MB !

**Comment by s4cha** [comment]
For reference I just found out about https://github.com/cmaitchison/git_diet which is really useful :)

**Comment by sdyalor** [comment]
Nice improvement, thank you for quick support.

![Screen Shot 2020-06-29 at 10 29 52 AM](https://user-images.githubusercontent.com/50224521/86025137-79361380-b9f3-11ea-83e3-c2602d3cc781.png)
