### ISSUE TITLE
Can't add the Stevia from swift package manager

### ISSUE THREAD

**Issue by sathya26d94** [freshOS/Stevia#149]
When I try to add Stevia to the package manager, I am getting the following error
<img width="1160" alt="Screenshot 2020-08-05 at 7 54 52 PM" src="https://user-images.githubusercontent.com/25863561/89424531-8a421500-d755-11ea-8fab-432cc7bfbd2b.png">

: terminated(128): CA_ASSERT_MAIN_THREAD_TRANSACTIONS=1 LOGNAME=sathya SHELL=/bin/zsh XPC_SERVICE_NAME=com.apple.dt.Xcode.8768 PATH=/Users/sathya/Downloads/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin __CF_USER_TEXT_ENCODING=0x1F6:0x0:0x0 CA_DEBUG_TRANSACTIONS=1 USER=sathya MallocNanoZone=0 TMPDIR=/var/folders/5z/22g_h1md3lx9jwz5bzx5dk980000gp/T/ SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.ZVTuDl7X0s/Listeners HOME=/Users/sathya XPC_FLAGS=0x0 /Users/sathya/Downloads/Xcode.app/Contents/Developer/usr/bin/git -C /Users/sathya/Library/Developer/Xcode/DerivedData/epiFi-dlrvtetqdyazhdbuqgjettcojatg/SourcePackages/repositories/grpc-swift-b0d8975a rev-parse --verify 'nio^{commit}' output:
    fatal: Needed a single revision

**Comment by s4cha** [comment]
Hi @sathya26d94 this is weird. Have you tried `Xcode` > `File` > `Swift Packages` > `Reset Package Caches` ?

**Comment by sathya26d94** [comment]
HI @s4cha, this issue is related to Swift package manager,  I have solved the issue.
