### ISSUE TITLE
Height equal height with multiplier.

### ISSUE THREAD

**Issue by NikKovIos** [freshOS/Stevia#162]
![image](https://user-images.githubusercontent.com/16647690/143078235-16d6b5cf-f199-49a4-afee-4a0257278eab.png)

    NSLayoutConstraint.activate([
        trimmerView.heightAnchor.constraint(equalTo: trimmerContainerView.heightAnchor, multiplier: 1/3)
    ])
How to achieve that with Stevia?

**Comment by s4cha** [comment]
The "equation" api enables you to write it like a math equation :
```swift
trimmerView.Height == trimmerContainerView.Height / 3
```

**Comment by gerchicov-vg** [comment]
@s4cha what about other APIs Stevia provide?
