### ISSUE TITLE
[Privacy Manifest] Implementation

### ISSUE THREAD

**Issue by corentios** [freshOS/Stevia#170]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by DmitryShapovalov** [comment]
Up! The same issue for me.

**Comment by s4cha** [comment]
Hey @corentios , Thanks for the update, apologies for taking so long to reply 😬. I am going to check it out this week. Stevia doesn't collect anything so it should be pretty straightforward to implement :)

**Comment by s4cha** [comment]
@corentios Privacy Manifest has been added in release [5.1.3](https://github.com/freshOS/Stevia/releases/tag/5.1.3). thanks again for raising the topic 👍

**Comment by corentios** [comment]
Thanks @s4cha !
