### ISSUE TITLE
Memory leask: '.tap' helper retains view in memory even after remove from superview

### ISSUE THREAD

**Issue by maximkhatskevich** [freshOS/Stevia#42]
The problem (and solution) is described here http://www.klundberg.com/blog/capturing-objects-weakly-in-instance-method-references-in-swift/

**Comment by s4cha** [comment]
@maximkhatskevich better late than never :p Thanks a ton for reporting this.
I played around and got another version working with `#selector` that gets rid of the nasty retain cycle.
However, after giving the some thought, I think the `tap` should be taken out of the lib completely. Indeed a tap helper is not part of a "Layout library" per se. the plan is to deprecate it and provide a working version on the side that people can use if they want to.

Let know if you have some thoughts,

**Comment by maximkhatskevich** [comment]
@s4cha completely agree! I always prefer Unix-style - single purpose done right per tool. I created a small library with helpers for UIControl event and gesture mapping that covers all you ever may need on iOS. Check this out: https://github.com/maximkhatskevich/MKHViewEvents/tree/master/Src

**Comment by s4cha** [comment]
Definitely agree ! Sweet ! Will play around with it when I have some time :)

PS : A new version of Stevia just came out !
Equations, Side Alignments & Percentage-based layouts 📏📐🎉
 -> https://github.com/freshOS/Stevia/releases/tag/3.1.0

**Comment by maximkhatskevich** [comment]
Wow, nice! Will check it out! Thanks for the tool, so far. Really great library, helps a lot, I can't develop UI without it anymore.

**Comment by s4cha** [comment]
@maximkhatskevich Sorry for taking so long to reply.
We need to deprecate this indeed, I was attracted by the simplicity at the time but it causes a retain cycle as you mentioned.
Since this is not part of the layout per-se. I think we should remove the `tap` helper all together.

We have a fallback solution, using selectors, cleaner and not producing retain cycles, that we could provide on the side for the ones wanting to opt out from the soon-to-be-deprecated `tap` function.

What do you think ?
By the way if you have a helper that you're using that you want to share, please do :)

**Comment by maximkhatskevich** [comment]
@s4cha as I posted earlier, yes, I agree that this functionality is not needed in Stevia and should be removed at all. The helpers I'm using are the same as I before - https://github.com/maximkhatskevich/MKHViewEvents

**Comment by cowgp** [comment]
I use the .tap closure extensively in my app, but I always declare self in the capture list as `[unowned self]`  This solves the retain issue, no?

**Comment by maximkhatskevich** [comment]
@cowgp probably, I didn't try, but that's not convenient, I usually pass a function, not an inline closure, so that would not work for me.

**Comment by s4cha** [comment]
@cowgp It does indeed :)

@maximkhatskevich my bad I forgot to re-read the discussion history :p

For inspiration, here is what we came up with a few months ago to replace the `tap` call in our App :

From the View Controller :
```swift
bindTap(of: v.nextButton, #selector(nextTapped))
```


implementation:
```swift
public extension UIViewController {
    
    public func bindTap(of button: UIButton, _ selector: Selector) {
        button.addTarget(self, action: selector, for: .touchUpInside)
    }
}
```

**Comment by maximkhatskevich** [comment]
@s4cha sure, that's the technic I use in my library as well. The point is that I don't like inconsistency in my code, so if I use one approach on defining bindings for controls - this approach should be universal, at least support all possible UIControlEvents via similar API. My library went even beyond that and allows you do add custom gesture recognizers to a control - all in one library. It doesn't make sense for me to bind 'tap' handler using Stevia extension, but when I need to bind handler for another event or add 'tap' handler to a UIImageView via UIGestureRecognizer - I have to use different techniques, such as standard UIKit API or another 3d party library. This is why I created https://github.com/maximkhatskevich/MKHViewEvents which covers all possible UIControl events (https://github.com/maximkhatskevich/MKHViewEvents/blob/master/Src/UIControl%2BBase.swift) as well as all possible UIView-based gesture recognizers (https://github.com/maximkhatskevich/MKHViewEvents/blob/master/Src/UIVIew%2BGestures.swift) in a consistent way without sacrificing any flexibility standard API can provide you. It does also includes several convenience aliases like 'tap' for UIButton, etc. (https://github.com/maximkhatskevich/MKHViewEvents/blob/master/Src/UIControl%2BAliases.swift) - the list of available aliases might be extended in future, push requests are welcome.

**Comment by s4cha** [comment]
@maximkhatskevich, definitely agree. When we deprecate it in the next version we'll make sure to link MKHViewEvents in the release notes  :)

**Comment by maximkhatskevich** [comment]
Great!

**Comment by waternotwords** [comment]
MKHViewEvents looks good, but before you link, it really should include at least basic usage in the readme file. The point of these awesome tools is to make things easier. Quickly deciding on whether an API is suitable should take as little time as possible :-)   Thanks again for this great project!

**Comment by maximkhatskevich** [comment]
@waternotwords you are right, a better Readme is coming to this and other my libraries in the coming weeks, definitely a week point of the lib so far.

**Comment by b1az** [comment]
@s4cha I wish you'd reconsider and leave _in_ syntactic sugar for UIControls. The main reason is that using Stevia implicitly does away with dragging/connecting @IBActions from .xib files to code. Even if Stevia is a great "View Layout Library", it would do even better if it gave developers a better API for UIControls. For instance, the existing README example is moot on how should view's `loginTapped()` communicate back to the action-handler, probably its view-controller:

```swift
func loginTapped() {
    //Do something
}
```

With the standard UIKit, we might resolve this with an injected property `let didTapLogin: () -> ()`. But it would be better if view-controller controlled the view inline, with the syntax-sugar that Stevia provides.

And of course remembering to do `[unowned self]` isn't nice, but is unavoidable even in existing UIKit approaches with injected action-property and trampoline functions. I wish there existed an `@unowned` attribute for a closure parameter at the callee/UIControl site - this would encode the fact that in these cases, no matter what block/closure is given to a UIControl, it should never be a strong reference as the UIControl is already referenced as a subview of a particular UIViewController's root-view. This would ensure that no strong references cycles occur.

I think having sugar for UIControls should be part of Stevia. And being a wholesome library would increase its chances to be a de facto alternative to the usual ways of Storyboards.

**Comment by s4cha** [comment]
Hello ! I think it's time to finally close this lifelong issue :D 
The `tap` helper has been deprecated for quite some time and it's time for it to go away.
@b1az I feel you man, there will always be pros and cons, that's what's hard with our job, it's always about choosing the right tradeoffs. As much I like the tap helper, I think it's too error prone until we get some sort of `@unowned` flag for closures as you pointed out.
As for the viewcontroller-viwe linking, I think this is now explained here: http://freshos.org/SteviaDocs/viewFromController/

If you want to keep using it, you can add this extension manually
```swift
//
//  Stevia+Tap.swift
//  LoginStevia
//
//  Created by Sacha Durand Saint Omer on 01/10/15.
//  Copyright © 2015 Sacha Durand Saint Omer. All rights reserved.
//

import UIKit

typealias ActionBlock = (() -> Void)?

class ClosureWrapper {
    var closure: ActionBlock
    
    init(_ closure: ActionBlock) {
        self.closure = closure
    }
}

private var kButtonBlockAssociationKey: UInt8 = 0
public extension UIButton {
    
    internal var testButtonBlock: ActionBlock {
        get {
            if let cw = objc_getAssociatedObject(self,
                                                 &kButtonBlockAssociationKey) as? ClosureWrapper {
                return cw.closure
            }
            return nil
        }
        set(newValue) {
            objc_setAssociatedObject(self,
                                     &kButtonBlockAssociationKey,
                                     ClosureWrapper(newValue),
                                     objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }
    
    /** Links UIButton tap (TouchUpInside) event to a block.
     
    Example Usage:
     
    ```
    button.tap {
        // do something
    }
    ```
     
    Or
    ```
    button.tap(doSomething)

    // later
    func doSomething() {
        // ...
    }
    ```
     
     - Returns: Itself for chaining purposes
     
     */
    @available(*, deprecated: 4.1.0,
                  message: "Use classic .addTarget(self, action: #selector(mySelector), for: .touchUpInside)")
    @discardableResult
    public func tap(_ block:@escaping () -> Void) -> UIButton {
        #if swift(>=2.2)
        addTarget(self, action: #selector(UIButton.tapped), for: .touchUpInside)
        #else
        addTarget(self, action: "tapped", forControlEvents: .TouchUpInside)
        #endif
        testButtonBlock = block
        return self
    }
    
    /** */
    @objc func tapped() {
        testButtonBlock?()
    }
}

```
Have a fantastic end of 2018 🥂 🎉

**Comment by NikKovIos** [comment]
Uh(
I was found this not long time ago and was happy, and its going to be deprecated so fast))

**Comment by NikKovIos** [comment]
@maximkhatskevich write a readme and how to use please

**Comment by maximkhatskevich** [comment]
@NikKovIos not sure what do you mean by "write a readme and how to use". My library "MKHViewEvents" has been renamed and moved to another location and the original links will redirect you to the new repo "XCEssentials/ViewEvents" where you can find ReadMe with examples of how to use. If you want to bind closures to your control events - look at https://github.com/vhesener/Closures framework.

**Comment by NikKovIos** [comment]
@maximkhatskevich great! I did enter to the old MKHViewEvents repo and it didn't redirect me.
