### ISSUE TITLE
Pod update fails with 2.3.0

### ISSUE THREAD

**Issue by navisingh** [freshOS/Stevia#58]
Pod update fails with 2.3.0

Analyzing dependencies
[!] Unable to satisfy the following requirements:
- `SteviaLayout (= 2.3.0)` required by `Podfile`

**Comment by s4cha** [comment]
@navisingh good catch, looks like [Stevia pod 2.3.0](https://cocoapods.org/?q=stevia) is not available through cocoapods

**Comment by s4cha** [comment]
@navisingh do you still have the issue?
