### ISSUE TITLE
MacOS/tvOS support

### ISSUE THREAD

**Issue by maximkhatskevich** [freshOS/Stevia#60]
Any ideas on how hard it is to make Stevia support macOS apps and tvOS? This is the best tool for defining auto layout, but I would like to use the same tool for all Apple platforms.

**Comment by s4cha** [comment]
HI @maximkhatskevich, haven't looked into it yet but it surely is a good idea! I'll let you know how it goes :)

**Comment by s4cha** [comment]
MacOS would need quite a lot of rewriting since it doesn't use UIKit so the methods need to be adapted for NSViews and then account for the differences, which I don't know yet, coming from iOS dev. TvOs on the other hand uses UIKit so if we build it for tvOs it should (theoretically) work out of the box :)
I'm going to start trying the tvOs support and will let you know how it goes.

**Comment by s4cha** [comment]
tvOS support is testable using : 
```
github "S4cha/Stevia" "c517b877b01cb68873d398fca35936420533296c"
```
Let me know what you think :)

**Comment by maximkhatskevich** [comment]
Yes, I understand about macOS support. Same here - I've been doing iOS only all my life and macOS seems to be very different, looks like it's not just about replacing "UIView" with "NSView".

Side note.
When I was thinking about this move - I thought it would be good to separate functionality about layout from helpers that implement adding subview, configuring views' styles and setting properties like event handlers, button.title, etc.

Thanks for tvOS support, I'll try when I have a chance and let you know if I have any difficulties.

**Comment by s4cha** [comment]
@maximkhatskevich, as agreed macOS is not in the roadmap but tvOS definitely is.
Closing this thread in favour of https://github.com/freshOS/Stevia/issues/68 to follow tvOS support.

Cheers,

**Comment by maximkhatskevich** [comment]
Okay, makes sense. I still wasn't able to try developing for tvOS yet, so don't have any feedback for you on this subject, sorry.
