### ISSUE TITLE
How to align horizontal views bottom rather than center ?

### ISSUE THREAD

**Issue by rayman-v** [freshOS/Stevia#61]
```
layout(
      0,
      |view1.size(100)-4-view2.size(40)
)
```

view1: height = 100
view2: height = 40

![image](https://cloud.githubusercontent.com/assets/4557143/18663393/f023a3b8-7f50-11e6-95e0-c11ff720c98f.png)

I want to align view2.bottom to view1.bottom, how?

**Comment by AnnieNinaJoyceV** [comment]
Any solution to this?

**Comment by rayman-v** [comment]
Not yet, I think this repo is not focus about vertical align problem,  so I use another repo solute it when I need to custom specify constrain.

**Comment by AnnieNinaJoyceV** [comment]
Do you mind sharing you fix? It will be very helpful.

**Comment by damien-nd** [comment]
For me what is what I do:

addConstraint(item: view2, attribute: . bottom, toItem: view1)

or for read you can add the default equal value like:

addConstraint(item: view2, attribute: . bottom, relatedBy: .equal, toItem: view1)


It is really easier to read and shorter than the default (but still works):

let c = NSLayoutConstraint(item: view2, attribute: .bottom, relatedBy: .equal, toItem: view1, attribute: .bottom, multiplier: 1.0, constant: 0.0)
addConstraint(c)


I hope it helps.

**Comment by rayman-v** [comment]
Using Cartography and Stevia to complement each other, I suggest.

**Comment by s4cha** [comment]
@rayman-v Happy to announce that this use case is now simplified in latest version https://github.com/freshOS/Stevia/releases/tag/3.1.0
```swift

layout(
      0,
      |view1.size(100)
)

alignBottoms(view1-4-view2.size(40))
```

```swift
alignBottoms(view1, view2)
```
If you ever prefer the equation style (which is longer in my opinion in this case), you could also use :
```swift
view1.Bottom == view2.Bottom
```
Hope this helps, have a fantastic day !

PS: You suggested above using both carthography and Stevia, would you have examples of use cases that are not supported by Stevia ?

**Comment by ChanchalW** [comment]
What if I want to keep view2 always in the bottom of view1.  Not bottom align, if view1 height ends at 250 then view2 should have an origin.y on 251

**Comment by s4cha** [comment]
@ChanchalW 

There are many ways to stack two views together vertically.


### Native Stackview
By using native `UIStackView`

### Use Equation Api
`view2.Top == view1.Bottom`

### Using layout
```swift
layout(
      view1,
      view2
)
```

You can find the full documentation here : https://github.com/freshOS/Stevia/wiki/2.-Layout

Let me know if this helps :)
