### ISSUE TITLE
Compiling error: Module file was created by an older version of the compiler; 

### ISSUE THREAD

**Issue by sfkaos** [freshOS/Stevia#64]
I am currently updating our software from XCode 7/Swift 2.x => XCode 8/Swift 3.

While trying to upgrade our SteviaLayout integration I've updated to 3.0.1. However, I'm currently receiving the following error on the SteviaLayout import statement:

```
Module file was created by an older version of the compiler; rebuilt 'SteviaLayout' and try again: /Users/<me>/.../SteviaLayout/SteviaLayout.framework/Modules/SteviaLayout.swiftmodule/x86_64.swiftmodule
```

I've tried `rm -rf ~/Library/Developer/Xcode/DerivedData/` and then rebuilding to no avail as has been suggested in a few SO inquiries. 

Would appreciate any and all help. 

If it helps I've added some code snippet

```
import UIKit

import SteviaLayout //=== Getting error here!! 

//===

class myView: UIView
{
    let imageView = UIImageView()
    let headerLabel = UILabel()
    let bodyLabel = UILabel()
    let chatButton = UIButton(type: .system)

    //===

    required
    convenience
    init()
    {
        self.init(frame: CGRect.zero)

        //===

        sv(

            imageView
                .style(imageViewStyle),

            headerLabel
                .style(headerLabelStyle),

            bodyLabel
                .style(bodyLabelStyle),

            chatButton
                .style(chatButtonStyle)
                .onTap(self, handler: #selector(self.chatHandler))
        )
    }
}
```

Please advise.

**Comment by navisingh** [comment]
Encountered the same issue.

**Comment by s4cha** [comment]
Hey @sfkaos @navisingh 
 
This should work now, 

This happens when local Xcode version is not the same as the one we built Stevia with.
To bypass this you can do :
`carthage update --no-use-binaries`  to force recompilation with the local version of Xcode

Hope this helps,
