### ISSUE TITLE
Prebuilt framework with Swift 3.0.1 ?

### ISSUE THREAD

**Issue by GenoZhou** [freshOS/Stevia#67]
Carthage uses Swift 3.0 prebuilt framework, which cause the problem of not able to be imported under Swift 3.0.1 environment (xcode8.1).
Suggest we to have prebuilt framework using Swift3.0.1.

**Comment by s4cha** [comment]
Hi @GenoZhou indeed this is an issue with the new Xcode, in the meantime you can use 
`carthage update --no-use-binaries`  to force recompilation with the local version of Xcode

Cheers,

**Comment by s4cha** [comment]
Hey @GenoZhou this should work without the trick above now :)

**Comment by GenoZhou** [comment]
yes，the latest release works as perfect.
S4cha <notifications@github.com>于2017年1月8日 周日下午2:51写道：
