### ISSUE TITLE
UICollectionView and UITableView

### ISSUE THREAD

**Issue by ianbradbury-bizzibody** [freshOS/Stevia#70]
Is it possible to use Stevia to layout cells?

**Comment by s4cha** [comment]
Sure, anything that is a UIView subclass :)
You can find example in the wiki : https://github.com/freshOS/Stevia/wiki/7.-TableView-Cells-&-CollectionView-Cells

**Comment by ianbradbury-bizzibody** [comment]
Thanks.  I haDN't seen the great documentation when I posted the issue.
