### ISSUE TITLE
Pin Left & Pin Right with Multiple Lines

### ISSUE THREAD

**Issue by csimmonsbluebook** [freshOS/Stevia#74]
For a uitableviewcell layout, how can you pin text to the left and text to the right with space in-between, but if the space in the text from the left will run into the text on the right, it will wrap to the next line.

I want it to look as follows:
<img width="366" alt="screen shot 2017-04-06 at 2 36 01 pm" src="https://cloud.githubusercontent.com/assets/19786779/24769984/6613d8e2-1ad6-11e7-8af2-99e2e890a59b.png">

I tried to implement this with the following code and other variations similar to it:
```
class AppointmentCell: UITableViewCell {

    var name = UILabel()
    var time = UILabel()

    required init?(coder aDecoder: NSCoder) { super.init(coder: aDecoder)}
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)

        sv(
            name.style(nameStyle),
            time
        )

        alignHorizontally(|-name.centerVertically()-""-time.centerVertically()-|)
    }

    func nameStyle(l:UILabel) {
        l.numberOfLines = 0
        l.textColor = .blue
    }
}
```

**Comment by s4cha** [comment]
Hi @csimmonsbluebook have you tried replacing -""- by `-(>=8)-` ?
I'll have time to help you out on monday :)

**Comment by csimmonsbluebook** [comment]
@s4cha Yes, I have tried that and it worked in most instances, but not others. See below:

![simulator screen shot apr 7 2017 2 37 44 pm](https://cloud.githubusercontent.com/assets/19786779/24814522/ee903782-1b9f-11e7-9d78-bfb327e2070d.png)

**Comment by s4cha** [comment]
Ok this looks like a compression priority.
You could rey to lower the second label sidra priority by playing with setcompressionResitance you can fond a great explanation here: https://krakendev.io/blog/autolayout-magic-like-harry-potter-but-real
Hope it helps ;)

**Comment by s4cha** [comment]
I meant lower the first label's priority *

**Comment by s4cha** [comment]
@csimmonsbluebook did setting `setcompressionResitance` solve your issue?

**Comment by csimmonsbluebook** [comment]
@s4cha Sorry for the delayed response. Read the article and that helped a lot. Thanks for linking it! Yes, using `time.setContentCompressionResistancePriority(UILayoutPriorityRequired, for: .horizontal)` worked perfectly.

**Comment by s4cha** [comment]
@csimmonsbluebook Glad it worked :) Have a fantastic day !
