### ISSUE TITLE
top/bottomLayoutGuide

### ISSUE THREAD

**Issue by timothyarmes** [freshOS/Stevia#79]
Hi,

How do you suggest we can use Stevia to constrain a view to the controller's top/bottom layout guides?

Currently, I'm having to do this:

````swift
func render() {
    sv(
        mainView,
        startButton
    )
        
    layout(
        0,
        mainView
        0
    )
        
   startButton.fillHorizontally(m: 20)
}
    
override func didMoveToSuperview() {
    startButton.bottomAnchor.constraint(equalTo: parentViewController!.bottomLayoutGuide.topAnchor, constant: -20).isActive = true
}
````

This works (thanks to the hack I'll describe below), but it's not nice to have to set up anchors separately in `didMoveToSuperview`. I suppose this will be improves with UIView's `safeAreaLayoutGuide` property in iOS 11, but I need a solution for iOS 10. Do you have a better one?

In general, it would be nice to reference `UILayoutGuide` and not just UIView when using Stevia.
In this example, it's a shame that I can't use Stevia to do this:

````swift
startButton.Bottom == parentViewController!.bottomLayoutGuide.Top
````

Similarly, we'll need to align to `safeAreaLayoutGuide` soon.

Thanks,

Tim

P.S. To make the hackiness of my solution above work, I had to add an extension to UIView to access the controller so that I could get the layout guides.

````swift
extension UIView {
    var parentViewController: UIViewController? {
        var parentResponder: UIResponder? = self
        while let responder = parentResponder {
            parentResponder = responder.next
            if let viewController = parentResponder as? UIViewController {
                return viewController
            }
        }
        return nil
    }
}
````

Arguably, views should never need to access their controller. In this case however I think it's justified - it makes more sense for a view to lay itself out that it does for the controller to lay out the view. I imagine that's way `safeAreaLayoutGuide` in in UIView, not the controller.

**Comment by s4cha** [comment]
@timothyarmes,

First off thanks for bringing that conversation to table :)
These are not supported at the moment as you noted out :/
Supporting `layout guides` and `safeAreaLayoutGuide` is definitely on our roadmap though and you are very welcome if you want to help.
I do share your view that they should be supported in Equation Api as well.

In the meantime I took some time to review your example and here is one way 
to make it less hacky :)

```swift
import UIKit
import Stevia

class ViewController: UIViewController {

    var v = View()
    override func loadView() { view = v }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Pass along bottomLayoutGuide to the View
        // this cannot be passed in it's initializer because
        // ViewController's bottomLayout guide is not yet set at this stage.
        v.bottomLayoutGuide = self.bottomLayoutGuide
        v.render()
        
        let toolBar = UIToolbar()
        view.addSubview(toolBar)
    }
}

class View: UIView {
    
    let mainView = UIView()
    let startButton = UIButton()
    var bottomLayoutGuide: UILayoutSupport!
    
    convenience init() {
        self.init(frame: CGRect.zero)
    }
    
    func render() {
        
        sv(
            mainView,
            startButton
        )

        layout(
            0,
            |mainView|,
            0
        )

        startButton.fillHorizontally(m: 20)
        
        // Hack can be replaced by this :)
        // It is still the view doing the layout, but without knowing about the VC in a hacky way :)
        startButton.bottomAnchor.constraint(equalTo: bottomLayoutGuide.topAnchor, constant: -20).isActive = true
        
        mainView.backgroundColor = .white
        startButton.backgroundColor = .yellow
    }
}
```

Please excuse the late reply, hope this helps :)

**Comment by s4cha** [comment]
Hi @timothyarmes!

Good news, support is coming for both `bottom/topLayoutGuide` (deprecated in iOS11)
and `safeAreaLayoutGuide` :)

Actually all `UILayoutSupport` & `UILayoutGuide` can be used in equations so
`readableContentGuide`, `layoutMarginsGuide` make it to the party as well.

You will be able to write :
`v.startButton.Bottom == bottomLayoutGuide.Top - 20`
from your controller 
and also 
`startButton.Bottom == safeAreaLayoutGuide.Bottom`
from within your view in iOS 11 

Have a fantastic day,

**Comment by s4cha** [comment]
https://github.com/freshOS/Stevia/releases/tag/4.1.0 

Let me know if that solves your issue :)

**Comment by s4cha** [comment]
@timothyarmes  can we close this now?
