### ISSUE TITLE
the tap method can only once?

### ISSUE THREAD

**Issue by ChendayUP** [freshOS/Stevia#81]
the tap method can only execute once?

**Comment by s4cha** [comment]
@ChendayUP yes, actually the `tap` helper is going to be deprecated in next version in favour of the classic way of doing it. The implementation is relying on Objc associated objects which feels a bit sketchy.

From your controller:
```swift
override func viewDidLoad() {
    super.viewDidLoad()
    v.loginButton.addTarget(self, action: #selector(login), for: .touchUpInside)
}

@objc
func login() {
    print("login button tapped")
}
```

hope it helps,
