### ISSUE TITLE
What is the type of normal SteviaMargins

### ISSUE THREAD

**Issue by Patrick3131** [freshOS/Stevia#88]
Hey,

I like the Framework a lot.

I want to keep one if my UIView classes as flexible as possible, therefore I want to create something like this:

```
var spacingBetweenLabels: Any? {
        willSet(newValue) {
            if newValue is SteviaFlexibleMargin {
                flexibleSpacingBetweenLabels = newValue as! SteviaFlexibleMargin
            } else if newValue is "SteviaMargin" {
                fixSpacingBetweenLabels = newValue as! "SteviaMargin"
                fixCustomSpacing = true
            }
        }
    }

```
But there is no SteviaMargin, and layout does not take Int or Double.
So I can later on choose the Layout settings between two views:

```
if fixCustomSpacing {
            layout(
                0,
                |UIView1-fixSpacingBetweenLabels-UIView2-|,
                0
            )
        } else {
            layout(
                0,
                |UIView1-fixSpacingBetweenLabels-UIView2-|,
                0
            )
        }
```

Can anybody tell me what type to use or how two achieve my goal?

Thanks!

**Comment by Patrick3131** [comment]
I got it, its CGFloat.

**Comment by s4cha** [comment]
@Patrick3131, Glad you found the solution.
Could you elaborate a bit what you're trying to achieve here? I've never seen such a use case and I am quite curious :)
