### ISSUE TITLE
UIStackView doesn't seem to play along

### ISSUE THREAD

**Issue by ntkon** [freshOS/Stevia#91]
Hi,
I'm using UIStackView with stevia but the padding doesn't seem to work. I know that stack views are special beasts, but not sure how to get the effect I need? For example:

`myStackView.Top == myContainerStackView.Top + 10`

doesn't add the +10 padding.

Any suggestions?

PS I love the library its so much better than story boards. 
PPS the stack views are in a UITableViewCell, in case that makes a difference.

**Comment by s4cha** [comment]
@ntkon  Could you paste your layout code? It's kinda hard to debug without it :)
PS: Please excuse the late reply ;)

**Comment by ntkon** [comment]
Hi @s4cha , also sorry for the late reply. I think my problem was that stackview naturally behaves differently to normal views. I've closed this off - sorry about that.
