### ISSUE TITLE
Support for UILabel baseline alignment

### ISSUE THREAD

**Issue by bellebethcooper** [freshOS/Stevia#93]
Hello,

Thanks for making Stevia! It has some ideas I'm really excited about (especially constraining multiple views at once, which I need to do a lot but is rare to find in a DSL for Auto Layout).

One thing I can't find mention of in the docs or the source code is support for aligning labels using their baseline attributes. Is this supported at all, or planned? And if not, is it possible for me to just mix and match a vanilla `NSLayoutConstraint` to cover my baseline needs and lay out the rest of my constraints in Stevia, or is there a better workaround?

Thanks!

**Comment by s4cha** [comment]
Hi @bellebethcooper,
Firstly thanks for the kind words, really glad you like it !

The use case is not (yet) supported since we covered the most common ones first, but it makes sense to have an api for that as well.

Stevia **is** pure auto layout so you can of course mix and use plain auto layout to align your labels in the mean time :)

Going to checkout at the use case and see what we can do :)

**Comment by s4cha** [comment]
Hey @bellebethcooper,

The introduced api would look like this:

```swift 
align(lastBaselines: label, label2, label3)
```

You can try it out before we add it 
```swift
@discardableResult
public func align(lastBaselines views: UIView...) -> [UIView] {
    return align(lastBaselines: views)
}

@discardableResult
public func align(lastBaselines views: [UIView]) -> [UIView] {
    for (i, v) in views.enumerated() where views.count > i+1 {
        let v2 = views[i+1]
        v.lastBaselineAnchor.constraint(equalTo: v2.lastBaselineAnchor).isActive = true
    }
    return views
}
```

This would also have a `firstBaseline` version, and an equation way of writing it such as 
`label.LastBaseline == label.LastBaseline`

Would such an api work for cover your needs ?

Cheers,

**Comment by bellebethcooper** [comment]
This looks perfect, thanks very much!

**Comment by s4cha** [comment]
You're welcome ! https://github.com/freshOS/Stevia/releases/tag/4.3.2
