### ISSUE TITLE
How to enable and disable centerX alignment

### ISSUE THREAD

**Issue by Shadester** [freshOS/Stevia#95]
I have a problem. I was able to remove Leading, Top and Bottom constraints. But I'm not able to remove CenterX constraints. How should I do that. I have something like this:

containerView.Top == 10 % self.Bottom

and 

containerView.CenterY == self.CenterY

and I want to be able to switch between one and the other on trait change (rotating an iPhone between portrait and landscape. How should I do that?

**Comment by s4cha** [comment]
@Shadester 
Very good point, `centerXConstraint` and `centerYConstraint` are not yet available.
I am going to add them in the future release.

In the mean time, you can use the following snippet 

public extension UIView {
        
    public var centerXConstraint: NSLayoutConstraint? {
        return constraintForView(self, attribute: .centerX)
    }
    
    public var centerYConstraint: NSLayoutConstraint? {
        return constraintForView(self, attribute: .centerY)
    }
}

func constraintForView(_ v: UIView, attribute: NSLayoutAttribute) -> NSLayoutConstraint? {
    let target = v.superview ?? v
    for c in target.constraints {
        if let fi = c.firstItem as? NSObject, fi == v && c.firstAttribute == attribute {
            return c
        }
        if let si = c.secondItem as? NSObject, si == v && c.secondAttribute == attribute {
            return c
        }
    }
    return nil
}
```

PS: Please excuse the long time it took to reply :)

**Comment by s4cha** [comment]
@Shadester  https://github.com/freshOS/Stevia/releases/tag/4.3.1 :)

**Comment by s4cha** [comment]
@Shadester exactly, in pseudocode, it might look like this :

```swift 
func onTraitChange() {
  if portrait {
    // Find & Remove previous constraint, add new one
    if let c = containerView.topConstraint { view.removeConstraint(c) }
    containerView.CenterY == self.CenterY
  } else {
    // Find & Remove previous constraint, add new one
    if let c = containerView.centerYConstraint { view.removeConstraint(c) }
    containerView.Top == 10 % self.Bottom
  }  
  view.layoutIfNeeded() 
}
```

Hope this helps :)

**Comment by s4cha** [comment]
Closing this for now, don't hesitate to reopen if needed :)
